name: flutter_web_worker_example
description: An absolute bare-bones flutter web app.

environment:
  sdk: "^3.3.0"
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  path: ^1.9.1
  drift:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  auto_route: ^9.3.0
  flutter_bloc: ^9.1.0
  provider: 6.1.2

  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.3
  auto_route_generator: ^9.3.0
  flutter_lints: ^5.0.0
  drift_dev:
dependency_override:
  provider: 6.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/data/word.json
    - assets/data/alternation.json